# Site settings
title: Setapak
email: info@se-tapak.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://se-tapak.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
